version: '3'

services:
  mysql:
    image: mysql:5
    volumes:
      - mysql5_data:/var/lib/mysql
      - mysql5_run:/var/run/mysql
    environment:
      MYSQL_ROOT_PASSWORD: verjbramn3
      MYSQL_DATABASE: pursed
    healthcheck:
        test: ["CMD", "mysqladmin", "--password=verjbramn3", "ping"]
        interval: 5s
        timeout: 15s
        retries: 4
        # needs version 3.4 start_period: 40s

  app:
    depends_on:
      - mysql
    build: src/
    image: djangosimplewallet
    working_dir: /src
    volumes:
      - mysql5_run:/var/run/mysql
    ports:
      - "8000:8000"
    environment:
      DOCKER_DATABASE_VERSION: 5
      DOCKER_DATABASE_URL: mysql://root:verjbramn3@mysql/pursed
    command: ./run.sh


volumes:
  mysql5_data:
  mysql5_run:
